### PR TITLE
Doc fixes

### PR DESCRIPTION
**Pull request by luketudge**
Small fixes for the documentation (#41 and #42 ).

### CODE REVIEW

**Comment by elizagrames** [comment]
Thanks for the doc fixes, Luke! Still getting around to the unexpected terms in the dfm.

**Comment by luketudge** [comment]
Great!

**Comment by luketudge** [comment]
@elizagrames thanks again for your work on the package. The reason that I have been active here is that a couple of my students are working with litsearchr and asked me for help with it. So I had to explore a bit and find out how it worked, and in doing so I encountered the minor issues that I have flagged so far.

I have finished writing a short explanation/tutorial for my students, and I have made it public. You can see it [here](https://luketudge.github.io/litsearchr-tutorial). I know that I have taken a lot of your time already, but just in case you are at a loose end sometime and feel like taking a look, you could let me know if there is anything I have got wrong about the package in the tutorial. And of course feel free to share or to suggest improvements. Thanks!

**Comment by elizagrames** [comment]
Oh wow, this is an amazing tutorial!! I love it! So cool to see everything laid out in an example from start to finish with explanations for students.

I'm working with @ameliakallaher and @rootsandberries on a [Library Carpentry lesson for litsearchr](https://github.com/ameliakallaher/lc-litsearchr) that also expands on the vignette. We would love to get your edits and thoughts for the lesson, especially since you've already figured out how to teach it to new users.

**Comment by luketudge** [comment]
Thanks. I'm really glad if it can be useful.

I just took a look at the carpentry pages. I like the explanations a lot, and especially the short exercises. So I don't have any edits to suggest for now. But I've watched the repo so I'll keep looking back if you add more.

Maybe also @Shireen87 can read it if she has time, and give you her thoughts from a student's perspective.

**Comment by Shireen87** [comment]
Yes sure I will check both tutorials, by Luke and the one on the carpentry page, then will give here my feedback. 
Thank you Luke and @elizagrames so much fo making our life easier!

**Pull request merged**
